### ISSUE TITLE
Commands?

### ISSUE THREAD

**Issue by supercrafter333** [HannesTheDev/CityBuildCommands#1]
Wo sind die Commands etc. Und eine bessere Beschreibung werde auch gut. Wenn du dieses Plugin auf poggit veröffentlichen möchtest, empfehle ich dir noch das ganze in english oder mit englisher config zu machen.

**Comment by HannesTheDev** [comment]
Ja, ich überlege noch ob och es veröffentliche also offieziel auf Poggit, habe halt erstmal Privat angefangen und bin auch schon fast fertig mit der BETA-1.0.0. Und ja ich werde auch noch eine Interessantere Bechreibung machen aber alles zu seiner Zeit.

**Comment by HannesTheDev** [comment]
Fertig
